feat: add etag middleware
hertz-contrib/etag pull request #1
Opened 2023-02-04 06:07 UTC by justlorain

#### What type of PR is this?

feat: A new feature

#### What this PR does / why we need it (en: English/zh: Chinese):

en: Add ETag middleware
zh: 添加 ETag 中间件

#### Which issue(s) this PR fixes:

Fixes (https://github.com/cloudwego/hertz/issues/504)

2023-02-05 16:37 UTC, li-jin-gou requested changes

2023-02-05 16:37 UTC, li-jin-gou commented on option.go
> +type Option func(o *Options)
add option unit test

2023-02-05 17:50 UTC, justlorain commented on option.go
> +type Option func(o *Options)
done, thx

2023-02-06 02:44 UTC, li-jin-gou commented
LGTM

2023-02-06 02:44 UTC, merged